### ISSUE TITLE
技术文档

### ISSUE THREAD

**Issue by kratosky** [YonminMa/SelectDormitory#1]
大佬你好，想参考一个类似这样的选工位系统，请问能否看看你的设计文档？谢谢！

**Comment by YonminMa** [comment]
系统没有做完，大部分内容都是边做边改，还没有最终版本的技术文档

**Comment by YonminMa** [comment]
https://www.apifox.cn/apidoc/shared-08881a39-bd7d-46fc-8c80-cf3f4a1b8aae
